apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-public-deployment
  labels:
    app: nginx-public
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-public
  template:
    metadata:
      labels:
        app: nginx-public
    spec:
      affinity:
       podAntiAffinity:
         requiredDuringSchedulingIgnoredDuringExecution:
         - labelSelector:
             matchExpressions:
             - key: app
               operator: In
               values:
               - nginx-public
           topologyKey: kubernetes.io/hostname
      initContainers:
      - name: check-private-nginx
        image: busybox
        command: ['sh', '-c', 'until wget http://nginx-private-service.default.svc.cluster.local; do echo waiting for priv nginx; sleep 2; done;']
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        readinessProbe:
        exec:
          command:
          - sh
          - -c
          - 'wget -T2 -O- http://nginx-private-service.default.svc.cluster.local'
        initialDelaySeconds: 5
        periodSeconds: 5
        
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-public-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: '60'
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  type: LoadBalancer
  selector:
    app: nginx-public
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80